# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import speechtotext_pb2 as speechtotext__pb2


class ConverterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.stream_unary(
                '/Converter/Convert',
                request_serializer=speechtotext__pb2.AudioSegment.SerializeToString,
                response_deserializer=speechtotext__pb2.Text.FromString,
                )


class ConverterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Convert(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.stream_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=speechtotext__pb2.AudioSegment.FromString,
                    response_serializer=speechtotext__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Converter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Converter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Convert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Converter/Convert',
            speechtotext__pb2.AudioSegment.SerializeToString,
            speechtotext__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
