# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechtotext.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12speechtotext.proto\"M\n\x0c\x41udioSegment\x12\x0f\n\x07\x61udioid\x18\x01 \x01(\x03\x12\x16\n\x0e\x61udiosegmentid\x18\x02 \x01(\x03\x12\x14\n\x0c\x61udiosegment\x18\x03 \x01(\x0c\"%\n\x04Text\x12\x0f\n\x07\x61udioid\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x03 \x01(\t2.\n\tConverter\x12!\n\x07\x43onvert\x12\r.AudioSegment\x1a\x05.Text(\x01\x62\x06proto3')



_AUDIOSEGMENT = DESCRIPTOR.message_types_by_name['AudioSegment']
_TEXT = DESCRIPTOR.message_types_by_name['Text']
AudioSegment = _reflection.GeneratedProtocolMessageType('AudioSegment', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOSEGMENT,
  '__module__' : 'speechtotext_pb2'
  # @@protoc_insertion_point(class_scope:AudioSegment)
  })
_sym_db.RegisterMessage(AudioSegment)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'speechtotext_pb2'
  # @@protoc_insertion_point(class_scope:Text)
  })
_sym_db.RegisterMessage(Text)

_CONVERTER = DESCRIPTOR.services_by_name['Converter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOSEGMENT._serialized_start=22
  _AUDIOSEGMENT._serialized_end=99
  _TEXT._serialized_start=101
  _TEXT._serialized_end=138
  _CONVERTER._serialized_start=140
  _CONVERTER._serialized_end=186
# @@protoc_insertion_point(module_scope)
